### PR TITLE
feat(`no-callback-in-promise`): add `timeoutsErr` option

### LINKED ISSUE #167: no-callback-in-promise misses callback passed as argument
### Description

The `no-callback-in-promise` rule only checks for [CallExpressions](https://github.com/xjamundx/eslint-plugin-promise/blob/5b935bdd3c3760a2e58eea9b89c86b6d3243e321/rules/lib/is-callback.js#L6). It does not check if a callback is passed to a third-party like `setTimeout(callback)`. I think any time a callback is passed to another function, the assumption should be that the callback will be called. 

### Steps to Reproduce

```js
function wait (callback) {
  return Promise.resolve()
    .then(() => {
      setTimeout(() => callback()); // this fails
      setTimeout(callback); // this does not fail
    }); 
}
```

**Expected behavior:** `no-callback-in-promise` flags error

**Actual behavior:** `no-callback-in-promise` rule does not flag error

### Versions

- Node version: 8
- ESLint version: 4.19.1
- eslint-plugin-promise version: 4.2.1

### Additional Information

Potential implementation: in https://github.com/xjamundx/eslint-plugin-promise/blob/5b935bdd3c3760a2e58eea9b89c86b6d3243e321/rules/lib/is-callback.js, you can potentially check if any of the CallExpressions's `arguments` [is a named callback](https://github.com/xjamundx/eslint-plugin-promise/blob/5b935bdd3c3760a2e58eea9b89c86b6d3243e321/rules/lib/is-named-callback.js).

### LINKED ISSUE #220: no-callback-in-promise use cases
It has been requested that we support these use cases in the `no-callback-in-promise` rule
```
    // TODO: support safe callbacks
    // 'whatever.then((err) => { process.nextTick(() => cb()) })',
    // 'whatever.then((err) => { setImmediate(() => cb())) })',
    // 'whatever.then((err) => setImmediate(() => cb()))',
    // 'whatever.then((err) => process.nextTick(() => cb()))',
    // 'whatever.then((err) => process.nextTick(cb))',
    // 'whatever.then((err) => setImmediate(cb))',
```

### PR DESCRIPTION
**Pull request by brettz9**
**What is the purpose of this pull request?**

- [x] Bug fix
- [x] Changes an existing rule

**What changes did you make? (Give an overview)**

- feat(`no-callback-in-promise`): add `timeoutsErr` option; fixes #167
- fix(`no-callback-in-promise`): ensure timeouts do not err (by default); fixes #220

### CODE REVIEW

**Comment by scagood** [comment]
I think the approach here may not be right, as we're looking for the timer functions with callbacks, not just timer functions.

eg if we use the [`node:timers/promises`](https://nodejs.org/api/timers.html#timers-promises-api) api, then timers are fine:

```js
import { setImmediate } from 'timers/promises';

whatever.then((err) => setImmediate('value'))
```

**Comment by brettz9** [comment]
Ah, good catch. Do you have a suggested way of catching those? Just introspecting on the imports for known promise APIs and failing otherwise?

**Comment by scagood** [comment]
The first way that comes to mind is using the [`ReferenceTracker`](https://eslint-community.github.io/eslint-utils/api/scope-utils.html#referencetracker-class) from our [`eslint-utils`](https://github.com/eslint-community/eslint-utils).

But I think that it is going about things the wrong way round

---

Maybe the check could be as simple as checking the scope of the variable and if it's got declarations?

**Comment by brettz9** [comment]
> The first way that comes to mind is using the [`ReferenceTracker`](https://eslint-community.github.io/eslint-utils/api/scope-utils.html#referencetracker-class) from our [`eslint-utils`](https://github.com/eslint-community/eslint-utils).
> 
> But I think that it is going about things the wrong way round
> 
> Maybe the check could be as simple as checking the scope of the variable and if it's got declarations?

You mean because a declaration would itself imply a potentially Promise-based library import as opposed to the built-ins?

**Comment by brettz9** [comment]
> I think the approach here may not be right, as we're looking for the timer functions with callbacks, not just timer functions.
> 
> eg if we use the [`node:timers/promises`](https://nodejs.org/api/timers.html#timers-promises-api) api, then timers are fine:
> 
> ```js
> import { setImmediate } from 'timers/promises';
> 
> whatever.then((err) => setImmediate('value'))
> ```

Actually, the code *is* only checking for timers with callbacks. Your example currently passes with the PR.

The main idea with the timeouts in this PR is to permit them unless the option `timeoutsErr: true` is set, and then, to only fail with them if the contain a callback (not to fail with their presence).

I was thinking you were suggesting that the following could be more acceptable with the option set:

```js
import { setImmediate } from 'timers/promises';
whatever.then((err) => setImmediate(cb))
```

...but I'm not sure that it is, as it is still passing around a callback inside of a promise.

**Comment by scagood** [comment]
> Actually, the code _is_ only checking for timers with callbacks. Your example currently passes with the PR.

Ah, that makes sense!

**Review by scagood — APPROVED** [review]
LGTM :+1:

**Review by ota-meshi — APPROVED** [review]
LGTM!

**Pull request merged**
