### PR TITLE
ci: swap release process to release-please

### LINKED ISSUE #506: Swap release process to release-please
I would personally be in favor of switching to a release please flow, like in https://github.com/eslint-community/eslint-plugin-n/pull/305, as that catches errors like this before release

This would help catch release errors like https://github.com/eslint-community/eslint-plugin-promise/issues/484#issuecomment-2247374199 before they actually get released

### PR DESCRIPTION
**Pull request by voxpelli**
**What is the purpose of this pull request?**

To improve the release process by swapping to release-please. Fixes #506

**What changes did you make? (Give an overview)**

Removed `cycjimmy/semantic-release-action` and added `googleapis/release-please-action`

### CODE REVIEW

**Comment by ota-meshi** [comment]
Do you think we also need to replace the version in package.json with `"7.0.0"`?

https://github.com/eslint-community/eslint-plugin-promise/blob/602d8254871e46c9d1808ee1a3a2c48cb7493334/package.json#L3

**Comment by voxpelli** [comment]
@ota-meshi Good point, fixed!

**Review by aladdin-add — APPROVED** [review]
👍

**Review by ota-meshi — APPROVED** [review]
I'm not familiar with the release-please config but it looks good to me. Thanks!

**Comment by voxpelli** [comment]
> I'm not familiar with the release-please config but it looks good to me. Thanks!

Its copied from `eslint-plugin-n` and `neostandard` :)

**Comment by brettz9** [comment]
> I'm not familiar with the release-please config but it looks good to me. Thanks!

Likewise...

**Pull request merged**
