### PR TITLE
docs: update README

### PR DESCRIPTION
**Pull request by Romick2005**
We need to add recommended value for no-multiple-resolved rule

**What is the purpose of this pull request?**

- [ x] Documentation update
- [ ] Bug fix
- [ ] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [ ] Other, please explain:

**What changes did you make? (Give an overview)**

### CODE REVIEW

**Comment by brettz9** [comment]
Is this a proposal to make the rule recommended? Because the rule is not currently a recommended rule and should therefore not be documented as such unless a change is made.

**Comment by Romick2005** [comment]
If it is not documented and is not explicitly stated as deprecated, then maybe we should just remove it?

**Comment by brettz9** [comment]
It is documented elsewhere on the page, but maybe it doesn't hurt to list all of the rules there in some fashion. But note that that list is not a recommended list--it is just indicating possible rules to pick from. The list of recommended rules is indicated later on the page.

**Review by brettz9 — APPROVED** [review]
LGTM

**Pull request merged**
