### PR TITLE
feat!: Bump all packages and fix linting

### PR DESCRIPTION
**Pull request by scagood**
**Larger Changes**

1. Drop support for `node` less than `^18.18.0` (this is inline with [eslint package.json:180](https://github.com/eslint/eslint/blob/main/package.json#L180))
1. Drop support for `eslint` less than `^7.0.0`

**Smaller Changes**

1. Migrate all message to messageId (for the update to eslint-plugin-eslint-plugin)
1. Bumped all packages (except eslint) to the latest version.
1. Replaced `eslint-plugin-node` with `eslint-plugin-n`
1. Replaced `npm-run-all` with `npm-run-all2`

### CODE REVIEW

**Comment by aladdin-add** [comment]
this is a breaking change.

**Comment by scagood** [comment]
> this is a breaking change.

The commits here are meant to be rebase merged, but its good that the title is representative of that too 😄

**Comment by aladdin-add** [comment]
what do you think splitting the PR to several smaller ones?

**Comment by scagood** [comment]
The only one I would split out would be [`9dcfd39` (#471)](https://github.com/eslint-community/eslint-plugin-promise/pull/471/commits/9dcfd39ace76293f107920c24324768cc4b9de8c)

However if that is the only way to convert the commits to changelog entries, I will split them into 4.

**Comment by brettz9** [comment]
@scagood : if you want to resolve the conflicts, I'd be happy to do a review. Also, can team members do merges if for another's PR, or is the merging reserved for team leaders?

**Pull request closed without merging**
